version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api
    ports: 
      - "8080:8080"
    depends_on:
      - "db"

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-db: